spring.application.name=discover_service

# Server configuration
server.port=${PORT}

# Firebase configuration
firebase.project.id=social-104a1
firebase.database.url=https://social-104a1-default-rtdb.firebaseio.com
firebase.storage.bucket=social-104a1.appspot.com

# Logging
logging.level.com.datn.discover_service=DEBUG
logging.level.org.springframework.web=INFO
logging.level.com.google.firebase=DEBUG 

# Database configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
